name: Deploy Mainnet

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  deploy:
    needs: test
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: mainnet
    secrets: inherit
