name: Deploy Testnet

on:
  release:
    types: [prereleased]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  deploy:
    needs: test
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: testnet
      wrangler-command: deploy
      message: ${{ github.event.release.tag_name || github.sha }}
    secrets: inherit
