name: Preview Testnet

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml

  preview:
    needs: test
    uses: ./.github/workflows/build-preview.yml
    with:
      environment: testnet
      message: "PR #${{ github.event.pull_request.number }}"
    secrets: inherit
